 ---------------------- Link Server T-SQL ----------------------

set identity_insert [vsr_SecurityParse].[dbo].[unified_import_queue] on

insert into [vsr_SecurityParse].[dbo].[unified_import_queue] ([ID]
      ,[NameSpace]
      ,[SourceFilePath]
      ,[SourceFileTimeStamp]
      ,[CloudFilePath]
      ,[SourceFileSize]
      ,[IsEmptyFile]
      ,[CreatedDate]
      ,[Status]
      ,[Type]
      ,[StageData]
      ,[SectionCount]
      ,[rowguid]
      ,[Filename])
SELECT  [ID]
      ,[NameSpace]
      ,[SourceFilePath]
      ,[SourceFileTimeStamp]
      ,[CloudFilePath]
      ,[SourceFileSize]
      ,[IsEmptyFile]
      ,[CreatedDate]
      ,[Status]
      ,[Type]
      ,[StageData]
      ,[SectionCount]
      ,[rowguid]
      ,[Filename]
    FROM OPENQUERY(DATA7, 'SELECT [ID]
      ,[NameSpace]
      ,[SourceFilePath]
      ,[SourceFileTimeStamp]
      ,[CloudFilePath]
      ,[SourceFileSize]
      ,[IsEmptyFile]
      ,[CreatedDate]
      ,[Status]
      ,[Type]
      ,[StageData]
      ,[SectionCount]
      ,[rowguid]
      ,[Filename] FROM vsr_SecurityParse.dbo.unified_import_queue where cast(Createddate as date) >= ''2024-10-24''') 
set identity_insert [vsr_SecurityParse].[dbo].[unified_import_queue] off
